import { EmailMessage } from "./types";

export const DEFAULT_SANDBOX_EMAILS: EmailMessage[] = [
  {
    id: "sb-1",
    from: "GitHub <noreply@github.com>",
    subject: "[GitHub] Please verify your device login",
    date: "July 9, 2026, 09:55 AM",
    snippet: "Hey omarshaat58, we detected a login attempt from a new IP address. Enter the following verification code to authorize this device...",
    body: "Hey omarshaat58,\n\nWe detected a login attempt to your GitHub account from a new browser or IP address.\n\nPlease enter the following verification code to authorize this device:\n\nGH-88410\n\nThis code is valid for 10 minutes. If you did not initiate this login, we recommend changing your password immediately.\n\nThanks,\nThe GitHub Security Team",
    category: "AUTH_CODE",
    summary: "GitHub login attempt detected; verification code is GH-88410.",
    isUrgent: true,
    verificationCode: "GH-88410",
    verificationService: "GitHub",
    suggestedAction: "Copy verification code",
  },
  {
    id: "sb-2",
    from: "Sarah Jenkins <sarah.jenkins@workplace.com>",
    subject: "URGENT: Review slides before client kickoff at 11:30",
    date: "July 9, 2026, 09:12 AM",
    snippet: "Hey, I noticed a discrepancy in the budget forecast numbers on Slide 4. We need to sync and fix this before the call at 11:30...",
    body: "Hi team,\n\nI was doing a final run-through of the pitch deck and noticed a major discrepancy in the budget forecast numbers on Slide 4. The Q3 projection is showing $450k instead of $540k, which conflicts with our financial summary sheet.\n\nWe absolutely need to sync and fix this before our client kickoff call at 11:30 AM today. Please review the shared slides immediately and make the correction if you have the spreadsheet open.\n\nLink to slides: https://docs.google.com/presentation/d/1x...",
    category: "URGENT",
    summary: "Major discrepancy found in pitch deck Slide 4; correction needed before the client call at 11:30 AM.",
    isUrgent: true,
    verificationCode: null,
    verificationService: null,
    suggestedAction: "Respond to sender",
  },
  {
    id: "sb-3",
    from: "British Airways <flightalerts@ba.com>",
    subject: "Flight BA-249 Heathrow to JFK Status Alert: Delayed",
    date: "July 9, 2026, 08:45 AM",
    snippet: "Important travel notice: Your flight BA-249 from London Heathrow (LHR) to New York (JFK) is delayed by 1 hour and 30 minutes...",
    body: "Dear Customer,\n\nWe are writing to inform you of a change in schedule for flight BA-249 from London Heathrow (LHR) to New York (JFK) departing today, July 9, 2026.\n\nYour flight is delayed by 1 hour and 30 minutes due to air traffic control restrictions. The new estimated departure time is 14:15. Check-in and bag drop times remain unchanged.\n\nWe apologize for any inconvenience this delay may cause to your travel plans.\n\nSincerely,\nBritish Airways Customer Operations",
    category: "URGENT",
    summary: "Flight BA-249 from Heathrow to JFK is delayed by 1 hour and 30 minutes; new departure is 14:15.",
    isUrgent: true,
    verificationCode: null,
    verificationService: null,
    suggestedAction: "Adjust travel plans",
  },
  {
    id: "sb-4",
    from: "Netflix <info@account.netflix.com>",
    subject: "Your Netflix temporary access code",
    date: "July 9, 2026, 08:30 AM",
    snippet: "Use this temporary access code to log in to your Netflix account. Your code is 591240. Never share this code...",
    body: "Hi there,\n\nHere is your temporary Netflix access code:\n\n591240\n\nEnter this code on your device to instantly sign in and start watching. It is valid for 15 minutes.\n\nIf you did not request this code, someone may be trying to log into your account. You can safely ignore this email or change your password to secure your account.\n\nThe Netflix Team",
    category: "AUTH_CODE",
    summary: "Netflix temporary login code is 591240.",
    isUrgent: true,
    verificationCode: "591240",
    verificationService: "Netflix",
    suggestedAction: "Copy authorization code",
  },
  {
    id: "sb-5",
    from: "David Miller <david.miller99@gmail.com>",
    subject: "Coffee tomorrow morning?",
    date: "July 9, 2026, 07:15 AM",
    snippet: "Hey, are we still on for our morning coffee tomorrow? Let me know if 9:00 AM works for you at the regular coffeehouse...",
    body: "Hey mate,\n\nHope you're having a good week!\n\nJust wanted to check if we are still on for our catch-up coffee tomorrow morning? Let me know if 9:00 AM works for you, or if you'd prefer to push it back to 9:30 AM. I'll be heading over to the usual local coffeehouse on 5th avenue.\n\nTalk soon,\nDavid",
    category: "NORMAL",
    summary: "David confirming if the morning coffee meetup tomorrow at 9:00 AM still works.",
    isUrgent: false,
    verificationCode: null,
    verificationService: null,
    suggestedAction: "Reply to sender",
  },
  {
    id: "sb-6",
    from: "Mega Brands Promo <marketing@offers.megabrands.com>",
    subject: "🔥 MEGA DEAL: 50% OFF everything, 12 hours only! Shop now!",
    date: "July 9, 2026, 06:00 AM",
    snippet: "Unbelievable prices! Get 50% off sitewide with free shipping. Electronics, clothes, furniture, and more inside...",
    body: "DEAL OF THE YEAR!\n\nFor 12 hours ONLY, we are slashing prices in half! Everything on our store is 50% off. No exceptions, no exclusions!\n\nUse coupon code MEGA50 at checkout.\n\nPlus, get FREE express shipping on all orders over $25!\n\nWhy wait? Shop electronics, style, fitness gear, and home goods today before stocks run dry!\n\nUnsubscribe from this list",
    category: "JUNK",
    summary: "Promotional blast offering 50% off sitewide using code MEGA50.",
    isUrgent: false,
    verificationCode: null,
    verificationService: null,
    suggestedAction: "Ignore advertisement",
  },
];
